[package]
name = "rust_test5"
version = "0.1.0"
authors = ["Wolfgang Reithmeier <wolfgang.reithmeier@bmw.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
